Dinit on freebsd-amd64 CI_task:
  skip: "changesIncludeOnly('.github/**',
                             'README.md',
                             'NEWS',
                             'BUILD*',
                             'CONTRIBUTORS',
                             'TODO',
                             'LICENSE',
                             'build/includes/README',
                             'doc/CODE-STYLE',
                             'doc/COMPARISON',
                             'doc/CONTRIBUTING',
                             'doc/DESIGN',
                             'doc/getting_started.md',
                             'doc/manpages/README',
                             'doc/manpages/generate-html.sh',
                             'doc/manpages/DINIT-AS-INIT.md',
                             'doc/linux/**')"
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-1
      - image_family: freebsd-12-4

  Getting depends_script: pkg update && ASSUME_ALWAYS_YES=YES pkg install gmake m4 file
  Print clang++ architecture_script: clang++ -dumpmachine
  Build_script: gmake
  Print dinit executive file architecture_script: file ./src/dinit
  Unit tests_script: gmake check
  Integration tests_script: gmake check-igr
