.TH DINIT "8" "June 2017" "Dinit 0.08" "Dinit \- service management system"
.SH NAME
dinit \- supervise processes and manage services
.\"
.SH SYNOPSIS
.\"
.B dinit
[\-s] [\-d \fIdir\fR] [\-p \fIpath\fR] [\fIservice-name\fR]
.\"
.SH DESCRIPTION
.\"
\fBDinit\fR is a process supervisor and service manager which can also
function as a system \fBinit\fR process. It has a small but functional
feature set, offering service dependency handling, parallel startup,
automatic rate-limited restart of failing processes, and service control
functions.

Dinit can be run as a system instance (when used as an \fBinit\fR or when
specified via command line parameter) or as a user instance. This affects
the default paths used to locate certain files, and the reaction to various
signals.

Dinit reads service descriptions from files located in the service
description directory, normally \fI/etc/dinit.d\fR for the system instance
or \fI$HOME/dinit.d\fR when run as a user process. See \fBSERVICE
DESCRIPTION FILES\fR for details.
.\"
.SH OPTIONS
.TP
\fB\-d\fR \fIdir\fP, \fB\-\-services\-dir\fR \fIdir\fP
Specifies \fIdir\fP as the directory containing service definition files.
.TP
\fB\-e\fR \fIfile\fP, \fB\-\-env\-file\fR \fIfile\fP
Read initial environment from \fIfile\fP. For the system init process, the
default is \fI/etc/dinit/environment\fR; for a user instance there is no
default. Values add to and replace variables present in the environment when
Dinit started.
.TP
\fB\-p\fR \fIpath\fP, \fB\-\-socket-path\fR \fIpath\fP
Species \fIpath\fP as the path to the control socket used to listen for
commands from the \fBdinitctl\fR program.
.TP
\fB\-s\fR, \fB\-\-system\fR
Run as the system init process. This is the default if invoked as PID 1.
This option affects the default service definition directory and
control socket path.
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fIservice-name\fR
Specifies the name of the service that should be started (along with its
dependencies). If not specified, defaults to \fIboot\fR (which requires
that a suitable service description for the \fIboot\fR service exists).
.\"
.SH SERVICE DESCRIPTION FILES
.\"
Service description files specify the parameters of each service. They are
named for the service they describe, and are found in \fI/etc/dinit.d\fR
for a system instance or \fI$HOME/dinit.d\fR for a user instance.

Service description files are read by Dinit on an "as needed" basis. Once a
service description has been read there is no way (yet) to alter it.

See \fBdinit-service\fR(5) for details of the format and available parameters.
.\"
.SH SIGNALS
.LP
When run as a system process, SIGINT stops all services and performs a reboot (on Linux, this signal can be
generated using the control-alt-delete key combination); SIGTERM stops services and halts the system; and
SIGQUIT performs an immediate shutdown with no service rollback.
.LP
When run as a user process, SIGINT and SIGTERM both stop services and exit Dinit; SIGQUIT exits Dinit
immediately.
.\"
.SH SEE ALSO
.\"
\fBdinitctl\fR(8), \fBdinit-service\fR(5).
.\"
.SH AUTHOR
Dinit, and this manual, were written by Davin McCall.
