#include <iostream>

#define STR2(arg) #arg
#define STR(arg)  STR2(arg)

static std::string stringify(std::string a)
{
    return std::string("\"") + a + "\"";
}

int main(int argc, char **argv)
{
    using namespace std;
    cout << "// This file is auto-generated by mconfig-gen.cc." << endl;
    cout << "const static char SYSCONTROLSOCKET[] =" << stringify(STR(SYSCONTROLSOCKET)) << ";" << endl;
    cout << "const static char SBINDIR[] = " << stringify(STR(SBINDIR)) << ";" << endl;
    return 0;
}
