name: Dinit on debian-bullseye-aarch64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Debian-bullseye-aarch64_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      name: Getting depends|configure|build|test
      with:
        arch: aarch64
        distro: bullseye
        run: | 
          apt-get update && apt-get install gcc make m4 g++ build-essential -y
          chmod +x ./configs/mconfig.Linux.sh
          ./configs/mconfig.Linux.sh
          make
          export LSAN_OPTIONS=verbosity=1:log_threads=1
          make check
#    - uses: uraimo/run-on-arch-action@v2
#      name: chmod +x configure
#      with:
#        arch: aarch64
#        distro: bullseye
#        run: chmod +x ./configs/mconfig.Linux.sh
#    - uses: uraimo/run-on-arch-action@v2
#      name: configure
#      with:
#        arch: aarch64
#        distro: bullseye
#        run: ./configs/mconfig.Linux.sh
#    - uses: uraimo/run-on-arch-action@v2
#      name: Build
#      with:
#        arch: aarch64
#        distro: bullseye
#        run: make
#    - uses: uraimo/run-on-arch-action@v2
#      name: Unit tests
#      with:
#        arch: aarch64
#        distro: bullseye
#        run: make check
## Integration tests disabled due some bugs
#    - uses: uraimo/run-on-arch-action@v2
#      name: Integration tests
#      with:
#        arch: aarch64
#        distro: bullseye
#        run: make check-igr
