name: Dinit on debian-sid-amd64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Debian-sid-amd64_build:

    runs-on: ubuntu-latest
    container:
      image: debian:sid

    steps:
    - uses: actions/checkout@v3
    - name: Getting depends
      run: apt-get update && apt-get install gcc make m4 g++ build-essential -y
    - name: chmod +x configure
      run: chmod +x ./configs/mconfig.Linux.sh
    - name: configure
      run: ./configs/mconfig.Linux.sh
    - name: Build
      run: make
    - name: Unit tests
      run: make check
## Integration tests disabled due some bugs
#    - name: Integration tests
#      run: make check-igr
