name: Dinit on debian-bullseye-aarch64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Debian-bullseye-aarch64_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Getting depends
      run: apt update && apt install g++-aarch64-linux-gnu make m4 -y
    - name: Linking /usr/bin/aarch64-linux-gnu-g++ to /usr/bin/g++
      run: ln -s /usr/bin/aarch64-linux-gnu-g++ /usr/bin/g++
    - name: Print g++ architecture
      run: g++ -dumpmachine
    - name: Chmod +x mconfig.Linux.sh
      run: chmod +x ./configs/mconfig.Linux.sh
    - name: Configure
      run: ./configs/mconfig.Linux.sh
    - name: Build
      run: make
    - name: make
    - uses: uraimo/run-on-arch-action@v2
      name: Unit tests
      with:
        arch: aarch64
        distro: bullseye
        run: | 
          export LSAN_OPTIONS=verbosity=1:log_threads=1
          make check
