name: Dinit on devuan-ceres-amd64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Devuan-ceres-amd64_build:

    runs-on: ubuntu-latest
    container:
      image: dyne/devuan:ceres

    steps:
    - uses: actions/checkout@v3
    - name: Getting depends
      run: apt-get update && apt-get install gcc make m4 g++ build-essential -y
    - name: chmod +x configure
      run: chmod +x ./configs/mconfig.Linux.sh
    - name: configure
      run: ./configs/mconfig.Linux.sh
    - name: Build
      run: make
    - name: Initial checks
      run: make check
    - name: Advanced checks
      run: make check-igr
