name: Dinit on macos-latest-amd64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  MacOS-latest-amd64_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print g++ architecture
      run: clang++ -dumpmachine
    - name: Build
      run: make
#    - name: Print dinit executive file architecture
#      run: file ./src/dinit
    - name: Unit tests
      run: make check
    - name: Integration tests
      run: make check-igr
