name: Dinit on macos-latest-amd64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  MacOS-latest-amd64_build:

    runs-on: macos-latest

    steps:
    - name: Test clang++
      run: clang++
    - name: Test m4
      run: m4 --version
