name: Dinit on macos-latest-amd64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  MacOS-latest-amd64_build:

    runs-on: macos-latest

    steps:
    - name: Getting Xcode depends
      run: xcode-select --install
