name: Dinit on macos-latest-amd64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  MacOS-latest-amd64_build:

    runs-on: macos-latest

    steps:
    - name: Getting homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Getting clang++ via homebrew
      run: brew install g++
