name: Dinit on ubuntu CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre_configure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: chmod +x configure
      run: chmod +x ./configs/mconfig.Linux.sh
    - name: configure
      run: ./configs/mconfig.Linux.sh
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make
  
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Initial checks
      run: make check
    - name: Advanced checks
      run: make check-igr
